version: '3.1'

# Description: Default compose file, run MusicBrainz Server without indexed search

volumes:
  pgdata:
    driver: local
  dbdump:
    driver: local
  searchdump:
    driver: local

services:
  db:
    build:
      context: build/postgres
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION:-12}
    image: musicbrainz-docker_db:${POSTGRES_VERSION:-12}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    restart: unless-stopped
    command: postgres -c "shared_buffers=2048MB" -c "shared_preload_libraries=pg_amqp.so"
    env_file:
      - ./default/postgres.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"

  musicbrainz:
    build:
      context: build/musicbrainz
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION:-12}
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "50"
    ports:
      - "${MUSICBRAINZ_WEB_SERVER_PORT:-5000}:5000"
    volumes:
      - dbdump:/media/dbdump
      - searchdump:/media/searchdump
    restart: unless-stopped
    env_file:
      - ./default/postgres.env
    environment:
      - MUSICBRAINZ_USE_PROXY=1
      - MUSICBRAINZ_SEARCH_SERVER=${MUSICBRAINZ_SEARCH_SERVER:-search.musicbrainz.org}
      - MUSICBRAINZ_WEB_SERVER_HOST=${MUSICBRAINZ_WEB_SERVER_HOST:-localhost}
      - MUSICBRAINZ_WEB_SERVER_PORT=${MUSICBRAINZ_WEB_SERVER_PORT:-5000}
    depends_on:
      - db
      - redis

  redis:
    image: redis:3-alpine
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    restart: unless-stopped
    expose:
      - "6379"
